export const WEB_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>QB Trace</title><link rel="stylesheet" href="/styles.css"></head>
<body><header><h1>QB Trace</h1><span id="recording">loading</span></header>
<div class="warning">Sensitive local data: Trace payloads are unredacted and may contain credentials, prompts, source code, and thinking.</div>
<main><section><h2>Overview</h2><div id="overview" class="cards"></div><h3>Storage by event type</h3><div id="types"></div></section>
<section class="workspace"><aside><h2>Sessions</h2><div id="sessions"></div><button id="moreSessions">More</button></aside>
<article><div class="toolbar"><h2>Timeline</h2><input id="eventType" placeholder="event type"><button id="filter">Filter</button><button id="live">Live: off</button></div><div id="timeline" class="timeline"><p>Select a session.</p></div><button id="moreEvents">More events</button></article>
<aside class="detail"><h2>Event detail</h2><pre id="detail">Select an event to load its payload.</pre></aside></section></main>
<div id="error" role="alert"></div><script src="/app.js"></script></body></html>`;

export const WEB_CSS = `:root{color-scheme:dark;font:14px ui-monospace,SFMono-Regular,Menlo,monospace;background:#111;color:#ddd}*{box-sizing:border-box}body{margin:0}header{display:flex;justify-content:space-between;padding:16px 22px;border-bottom:1px solid #333}h1,h2,h3{margin:.3em 0}.warning{padding:10px 22px;background:#4b2d00;color:#ffd79a}main{padding:16px 22px}.cards{display:flex;gap:10px;flex-wrap:wrap}.card{padding:12px;background:#1d1d1d;border:1px solid #333;border-radius:6px}.workspace{display:grid;grid-template-columns:260px minmax(360px,1fr) minmax(320px,40%);gap:14px;margin-top:18px}.workspace>aside,.workspace>article{border:1px solid #333;padding:12px;min-height:60vh;overflow:auto}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.toolbar h2{margin-right:auto}button,input{background:#222;color:#ddd;border:1px solid #555;padding:7px;border-radius:4px}.session,.event{display:block;width:100%;text-align:left;background:transparent;border:0;border-bottom:1px solid #292929;padding:8px}.session:hover,.event:hover{background:#222}.selected{background:#263445}.meta{color:#888;font-size:12px}.event .error{color:#ff7777}pre{white-space:pre-wrap;word-break:break-word;font-size:12px}#error{position:fixed;bottom:10px;right:10px;background:#742;padding:10px;display:none}@media(max-width:1000px){.workspace{grid-template-columns:220px 1fr}.detail{grid-column:1/-1;min-height:300px!important}}`;

export const WEB_JS = `(()=>{'use strict';
const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('token')){sessionStorage.setItem('qb-trace-token',hash.get('token'));history.replaceState(null,'',location.pathname)}
const token=sessionStorage.getItem('qb-trace-token')||'';const state={session:null,sessionCursor:null,eventCursor:null,liveAbort:null};
const el=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path){const r=await fetch(path,{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw new Error((await r.text())||('HTTP '+r.status));return r.json()}
function fail(e){el('error').textContent=e.message||String(e);el('error').style.display='block';setTimeout(()=>el('error').style.display='none',5000)}
function size(n){for(const u of ['B','kB','MB','GB']){if(n<1000||u==='GB')return (u==='B'?n:n.toFixed(1))+' '+u;n/=1000}}
async function overview(){const [s,t]=await Promise.all([api('/api/v1/status'),api('/api/v1/stats/event-types')]);el('recording').textContent=s.recording?'● trace on':'○ trace off';el('overview').innerHTML=[['Events',s.overview.eventCount],['Payload',size(s.overview.payloadBytes)],['Database',size(s.databaseSizeBytes)],['Dropped',s.diagnostics.droppedEvents],['Errors',s.diagnostics.storageErrors]].map(x=>'<div class="card"><b>'+esc(x[0])+'</b><div>'+esc(x[1])+'</div></div>').join('');el('types').innerHTML=t.items.slice(0,12).map(x=>'<div>'+esc(x.eventType)+' — '+x.eventCount+' / '+size(x.payloadBytes)+'</div>').join('')||'<p>No events.</p>'}
async function sessions(reset=false){if(reset){state.sessionCursor=null;el('sessions').innerHTML=''}const p=new URLSearchParams({limit:'50'});if(state.sessionCursor)p.set('cursor',state.sessionCursor);const d=await api('/api/v1/sessions?'+p);state.sessionCursor=d.nextCursor||null;for(const s of d.items){const b=document.createElement('button');b.className='session';b.innerHTML='<b>'+esc(s.cwd||s.sessionId)+'</b><div class="meta">'+esc(s.model||'no model')+' · '+s.eventCount+' events · '+esc(s.lastTimestamp)+'</div>';b.onclick=()=>selectSession(s.sessionId,b);el('sessions').appendChild(b)}el('moreSessions').style.display=state.sessionCursor?'block':'none'}
async function selectSession(id,b){state.session=id;state.eventCursor=null;document.querySelectorAll('.session').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');el('timeline').innerHTML='';stopLive();await events()}
function eventParams(){const p=new URLSearchParams({limit:'50'});if(state.eventCursor)p.set('cursor',state.eventCursor);const type=el('eventType').value.trim();if(type)p.set('eventType',type);return p}
async function events(reset=false){if(!state.session)return;if(reset){state.eventCursor=null;el('timeline').innerHTML=''}const d=await api('/api/v1/sessions/'+encodeURIComponent(state.session)+'/events?'+eventParams());state.eventCursor=d.nextCursor||null;for(const e of d.items)addEvent(e);el('moreEvents').style.display=state.eventCursor?'block':'none'}
function addEvent(e,prepend=false){const b=document.createElement('button');b.className='event';b.innerHTML='<b class="'+(e.isError?'error':'')+'">'+esc(e.eventType)+'</b><div class="meta">'+esc(e.timestamp)+' · turn '+esc(e.turnIndex??'-')+' · '+size(e.payloadBytes)+'</div>';b.onclick=()=>detail(e.eventId);prepend?el('timeline').prepend(b):el('timeline').appendChild(b)}
async function detail(id){const d=await api('/api/v1/events/'+encodeURIComponent(id));let payload;try{payload=JSON.parse(d.payloadJson)}catch{payload=d.payloadJson}el('detail').textContent=JSON.stringify({...d,payloadJson:undefined,payload},null,2)}
function stopLive(){state.liveAbort?.abort();state.liveAbort=null;el('live').textContent='Live: off'}
async function live(){if(state.liveAbort){stopLive();return}if(!state.session)return;const c=new AbortController();state.liveAbort=c;el('live').textContent='Live: on';try{const p=new URLSearchParams({sessionId:state.session});const r=await fetch('/api/v1/events/stream?'+p,{headers:{Authorization:'Bearer '+token},signal:c.signal});if(!r.ok)throw new Error(await r.text());const reader=r.body.getReader();const dec=new TextDecoder();let buf='';while(true){const x=await reader.read();if(x.done)break;buf+=dec.decode(x.value,{stream:true});let i;while((i=buf.indexOf('\n\n'))>=0){const block=buf.slice(0,i);buf=buf.slice(i+2);const line=block.split('\n').find(x=>x.startsWith('data: '));if(line){const data=JSON.parse(line.slice(6));for(const e of data.items||[])addEvent(e,true)}}}}catch(e){if(!c.signal.aborted)fail(e)}finally{if(state.liveAbort===c)stopLive()}}
el('moreSessions').onclick=()=>sessions().catch(fail);el('moreEvents').onclick=()=>events().catch(fail);el('filter').onclick=()=>events(true).catch(fail);el('live').onclick=()=>live();Promise.all([overview(),sessions(true)]).catch(fail);setInterval(()=>overview().catch(fail),5000);
})();`;
